baseURL = "https://golhaprogram.com"
title = "برنامه‌ی گلها"
theme = "PaperMod"
defaultContentLanguage = "fa"

# Enable Persian characters in URLs
disablePathToLower = true
removePathAccents = false

# Content organization
contentDir = "content"

# URL/Output configuration
uglyURLs = false
canonifyURLs = true

[languages.fa]
languageName = "فارسی"
languageCode = "fa"
weight = 1

[languages.fa.params]
rtl = true

[permalinks]
programs = "/:section/:contentbasename/"
singers = "/singers/:slug/"
players = "/players/:slug/"
poets = "/poets/:slug/"
announcers = "/announcers/:slug/"
composers = "/composers/:slug/"
arrangers = "/arrangers/:slug/"

[taxonomies]
dastgah = "dastgahs"
singer = "singers"
poet = "poets"
player = "players"
announcer = "announcers"
composers = "composers"
arrangers = "arrangers"

[menu]
[[menu.main]]
name = "خانه"
url = "/"
weight = 1

[[menu.main]]
name = "برنامه‌ها"
url = "/programs/"
weight = 2

[[menu.main]]
name = "درباره"
url = "/about/"
weight = 3

[build]
writeStats = true

[build.buildStats]
enable = true

[module]
[[module.mounts]]
source = "assets"
target = "assets"
[module.hugoVersion]
extended = true

[minify]
minifyOutput = true

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isPlainText = true
notAlternative = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[outputFormats.Sitemap]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = false
noUgly = true
rel = "sitemap"

[outputs]
home = ["HTML", "JSON", "RSS", "Sitemap", "ROBOTS"]

[outputFormats.ROBOTS]
mediatype = "text/plain"
baseName = "robots"
isPlainText = true
notAlternative = true

[params]
# Common parameters
audioHost = "music.golhaprogram.com"
description = "آرشیو کامل برنامه‌های ماندگار رادیو ایران شامل گلهای رنگارنگ، گلهای تازه، گلهای جاویدان، برگ سبز و یک شاخه گل. مجموعه‌ای ارزشمند از موسیقی و شعر کلاسیک ایرانی."
defaultImage = "/images/golha-og-image.jpg"  # Default image for social sharing
twitter = "golhaprogram"  # Twitter username without @
