baseURL = "https://golhaprogram.com"
title = "برنامه‌ی گلها"
theme = "PaperMod"
defaultContentLanguage = "fa"

# Enable Persian characters in URLs
disablePathToLower = true
removePathAccents = false

# Content organization
contentDir = "content"

# URL/Output configuration
uglyURLs = false
canonifyURLs = true

[languages.fa]
languageName = "فارسی"
languageCode = "fa"
weight = 1

[languages.fa.params]
rtl = true

[permalinks]
  programs = "/:section/:sections[last]/:filename/"
  singers = "/singers/:slug/"
  players = "/players/:slug/"
  poets = "/poets/:slug/"
  announcers = "/announcers/:slug/"

[taxonomies]
  dastgah = "dastgahs"
  singer = "singers"
  poet = "poets"
  player = "players"
  announcer = "announcers"


[menu]
[[menu.main]]
name = "خانه"
url = "/"
weight = 1

[[menu.main]]
name = "برنامه‌ها"
url = "/programs/"
weight = 2

[[menu.main]]
name = "درباره"
url = "/about/"
weight = 3

[build]
  writeStats = true


[build.buildStats]
  enable = true

[build.processing]
  js = true
  html = true

[build.processing.css]
  includePaths = ["assets/css"]

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [module.hugoVersion]
    extended = true


[minify]
  minifyOutput = true

  [minify.css]
    includePaths = ["assets/css"]

