baseURL = "https://golhaprogram.com"
title = "برنامه‌ی گلها"
theme = "PaperMod"
defaultContentLanguage = "fa"

# Enable Persian characters in URLs
disablePathToLower = true
removePathAccents = false

# Content organization
contentDir = "content"

# URL/Output configuration
uglyURLs = false
canonifyURLs = true

[languages.fa]
languageName = "فارسی"
languageCode = "fa"
weight = 1

[languages.fa.params]
rtl = true

[permalinks]
  programs = "/:section/:sections[last]/:filename/"
