[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.139.2"
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Production context (main branch)
[context.production]
  command = "hugo --gc --minify -e production"

# Beta context
[context.beta]
  command = "hugo --gc --minify -e beta"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[dev]
  framework = "hugo"
  targetPort = 1313