# Base configuration for all branches
[build]
publish = "public"
command = "hugo --gc --minify -e production"

[build.environment]
HUGO_VERSION = "0.139.2"
NODE_VERSION = "20"
NPM_VERSION = "10"
HUGO_ENABLEGITINFO = "true"

[build.buildStats]
enable = true

[build.processing]
js = true
html = true

[build.processing.css]
includePaths = ["assets/css"]

# Production context: main branch
[context.production]
command = "npm run build:js && hugo --gc --minify --environment production"

[context.production.environment]
HUGO_ENV = "production"
NODE_ENV = "production"

# Beta context: beta branch
[context.beta]
command = "npm run build:js && hugo --gc --minify --environment beta"

[context.beta.environment]
HUGO_ENV = "beta"
NODE_ENV = "production"

# Branch deploys (when pushing to a branch other than main or beta)
[context.branch-deploy]
command = "npm run build:js && hugo --gc --minify --environment beta"

[context.branch-deploy.environment]
HUGO_ENV = "beta"
NODE_ENV = "production"

[context.branch-deploy.processing]
skip_processing = false

# Deploy Previews (when creating a pull request)
[context.deploy-preview]
command = "npm run build:js && hugo --gc --minify --environment beta"

[context.deploy-preview.environment]
HUGO_ENV = "beta"
NODE_ENV = "production"

[context.deploy-preview.processing]
skip_processing = false


# 404 page handling
[[redirects]]
from = "/*"
to = "/404.html"
status = 404

# Dev setting
[dev]
framework = "hugo"
targetPort = 1313
