# Base configuration for all branches
[build]
publish = "public"
command = "hugo --gc --minify -e $HUGO_ENV"

[build.environment]
HUGO_VERSION = "0.139.2"
NODE_VERSION = "20"
NPM_VERSION = "10"
HUGO_ENABLEGITINFO = "true"

[build.buildStats]
enable = true

[build.processing]
js = true
html = true

[build.processing.css]
includePaths = ["assets/css"]

# Production context: main branch
[context.production]
command = "hugo --gc --minify -e production"

[context.production.environment]
HUGO_ENV = "production"

# Beta context: beta branch
[context.beta]
command = "hugo --gc --minify -e beta"

[context.beta.environment]
HUGO_ENV = "beta"

# Default context (for branch deploys)
[context.branch-deploy]
command = "hugo --gc --minify -e branch-deploy"

[context.branch-deploy.environment]
HUGO_ENV = "branch-deploy"

# Default context (when deploying to PR)
[context.deploy-preview]
command = "hugo --gc --minify -e deploy-preview"

[context.deploy-preview.environment]
HUGO_ENV = "deploy-preview"

# 404 page handling
[[redirects]]
from = "/*"
to = "/404.html"
status = 404

# Dev setting
[dev]
framework = "hugo"
targetPort = 1313
