baseURL = "/"

[params]
noindex = true

[params.remark42]
commentsHost = "comments-beta.golhaprogram.com"
commentsSiteId = "golhaprogram"

[params.plausible]
enable = false
domain = "golhaprogram.com"
# Default script URL, can be changed for self-hosted instances
scriptURL = "https://plausible.io/js/script.js"
