baseURL = "https://golhaprogram.com"

[params]
noindex = false
enableCSP = false  # Set to true to enable CSP, false to disable

[params.remark42]
commentsHost = "comments.golhaprogram.com"
commentsSiteId = "golhaprogram"

[params.plausible]
enable = true
domain = "golhaprogram.com"
# Default script URL, can be changed for self-hosted instances
scriptURL = "https://plausible.io/js/pa-r3J1GffenhOYfJaUkX1Ux.js" 
