baseURL = "https://golhaprogram.com"

[params]
noindex = false

[params.remark42]
commentsHost = "comments.golhaprogram.com"
commentsSiteId = "golhaprogram"

[params.plausible]
enable = true
domain = "golhaprogram.com"
# Default script URL, can be changed for self-hosted instances
scriptURL = "https://plausible.io/js/script.js"
