baseURL = "https://golhaprogram.com"

[params]
noindex = false
enableCSP = false  # Set to true to enable CSP, false to disable

[params.remark42]
commentsHost = "comments.golhaprogram.com"
commentsSiteId = "golhaprogram"

[params.plausible]
enable = true
scriptURL = "https://plausible.io/js/pa-r3J1GffenhOYfJaUkX1Ux.js" 

[params.umami]
enable = true
scriptURL = "https://cloud.umami.is/script.js"
dataWebsiteId = "88ad3b34-cf8e-4f6d-adce-f33cde48f580" 
